sudo: False

language: python

matrix:
  include:
    - python: 3.6

install:
  # Install conda
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no

  # Install dependencies
  - conda create -n test -c conda-forge python=$TRAVIS_PYTHON_VERSION pip
  - source activate test
  - export BOTO_CONFIG=/dev/null
  - export AWS_ACCESS_KEY_ID=foobar_key
  - export AWS_SECRET_ACCESS_KEY=foobar_secret
  - conda install boto3 botocore httpretty moto six pytest mock -c conda-forge -y
  - pip install git+https://github.com/martindurant/filesystem_spec/ --no-deps
  - pip install -r test_requirements.txt

script:
  - py.test -vv s3fs

notifications:
  email: false
